version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /home/ubuntu/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - 80:80
      - 22:22
      - 443:443
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'

  jfrog:
    image: 'docker.bintray.io/jfrog/artifactory-oss:6.23.13'
    container_name: artifactory
    restart: always
    ports:
      - 8081:8081
    volumes:
      - 'artifactory:/var/opt/jfrog/artifactory'
      - /etc/localtiime:/etc/localtime:ro

volumes:
  artifactory:
